version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    command: uvicorn main:app --host 0.0.0.0 --port 80

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web